<a href="https://colab.research.google.com/github/Shivambharti28/Movie-Recommendation-System/blob/main/Movies.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import ast
import warnings
warnings.filterwarnings('ignore')

In [4]:
df = pd.read_csv('AI_movies_dataset.csv')
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [5]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8965 entries, 0 to 8964
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  8965 non-null   bool
 1   belongs_to_collection  1273 non-null   object
 2   budget                 8965 non-null   int64
 3   genres                 8965 non-null   object
 4   homepage               565 non-null    object
 5   id                     8965 non-null   int64
 6   imdb_id                8965 non-null   object
 7   original_language      8965 non-null   object
 8   original_title         8965 non-null   object
 9   overview               8940 non-null   object
 10  popularity             8965 non-null   float64
 11  poster_path            8934 non-null   object
 12  production_companies   8965 non-null   object
 13  production_countries   8965 non-null   object
 14  release_date           8960 non-null   object
 15  revenue                8965 non-null   int64
 16  runtime                8959 non-null   float64
 17  spoken_languages       8965 non-null   object
 18  status                 8958 non-null   object
 19  tagline                6378 non-null   object
 20  title                  8964 non-null   object
 21  video                  8964 non-null   object
 22  vote_average           8964 non-null   float64
 23  vote_count             8964 non-null   float64
dtypes: bool(1), float64(4), int64(3), object(16)
memory usage: 1.6+ MB

In [7]:
df.shape

(8965, 24)

In [8]:
df.isnull().sum()

adult                       0
belongs_to_collection    7692
budget                      0
genres                      0
homepage                 8400
id                          0
imdb_id                     0
original_language           0
original_title              0
overview                   25
popularity                  0
poster_path                31
production_companies        0
production_countries        0
release_date                5
revenue                     0
runtime                     6
spoken_languages            0
status                      7
tagline                  2587
title                       1
video                       1
vote_average                1
vote_count                  1
dtype: int64

In [9]:
df = df.drop_duplicates().reset_index(drop=True)

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df = df[['title','overview','genres','tagline','vote_average','popularity']]

In [12]:
df

,title,overview,genres,tagline,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",NaN,7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",Roll the dice and unleash the excitement!,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",Still Yelling. Still Fighting. Still Ready for...,6.5,11.712900
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",Friends are the people who let you be yourself...,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'id': 35, 'name': 'Comedy'}]",Just When His World Is Back To Normal... He's ...,5.7,8.387519
...,...,...,...,...,...,...
8959,Days of Being Wild,The movie is set in Hong Kong and the Philippi...,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",NaN,7.3,6.242263
8960,Across the Tracks,When Billy returns from reform school he has t...,"[{'id': 18, 'name': 'Drama'}]",NaN,5.5,1.437157
8961,Begotten,"Begotten is the creation myth brought to life,...","[{'id': 14, 'name': 'Fantasy'}, {'id': 27, 'na...",NaN,5.0,2.592052
8962,Life on a String,Two blind men pursue ephemeral and unlikely ho...,"[{'id': 18, 'name': 'Drama'}, {'id': 10769, 'n...",NaN,7.0,0.071589
8963,NaN,"As punishment for drunken, rebellious behavior...","[{'id': 18, 'name': 'Drama'}]",Sometim,NaN,5.450197

In [13]:
df.isnull().sum()

title              1
overview          25
genres             0
tagline         2587
vote_average       1
popularity         0
dtype: int64

In [14]:
df = df.dropna(subset=['title']) # --> droping rows of title with null values

In [15]:
df['overview'] = df['overview'].fillna(' ') # --> placing blank space in place of null values in overview

In [16]:
df.iloc[0]['genres']

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [17]:
df['genres']=df['genres'].apply(lambda x:" ".join([i['name'] for i in ast.literal_eval(x)])) # --> filtering genre

In [18]:
df.head()

,title,overview,genres,tagline,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,NaN,7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.712900
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519

In [19]:
df['tagline'] = df['tagline'].fillna(' ') # --> placing blank space in place of null values in tagline

In [20]:
df.isnull().sum()

title           0
overview        0
genres          0
tagline         0
vote_average    0
popularity      0
dtype: int64

In [21]:
df['tags'] = df['overview'] + " " + df['genres'] + " " + df['tagline'] # --> Adds new column

In [22]:
df.head()

,title,overview,genres,tagline,vote_average,popularity,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,7.7,21.946943,"Led by Woody, Andy's toys live happily in his ..."
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539,When siblings Judy and Peter discover an encha...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.712900,A family wedding reignites the ancient feud be...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495,"Cheated on, mistreated and stepped on, the wom..."
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519,Just when George Banks has recovered from his ...

# **NATURAL LANGUAGE PROCESSING**

In [23]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [24]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [25]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [26]:
def preprocess_text(text):
  text = str(text).lower() # --> lowercase
  text = re.sub(r'[^a-zA-Z\s]', '',text) # --> removed the punctuations

  words = text.split()

  # remove stopwords
  words = [word for word in words if word not in stop_words]

  #lemmatize
  words = [lemmatizer.lemmatize(word) for word in words]

  return " ".join(words) # --> list to string conversion

In [27]:
df['tags'] = df['tags'].apply(preprocess_text)

In [28]:
df.head()

,title,overview,genres,tagline,vote_average,popularity,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,7.7,21.946943,led woody andys toy live happily room andys bi...
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539,sibling judy peter discover enchanted board ga...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.712900,family wedding reignites ancient feud nextdoor...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495,cheated mistreated stepped woman holding breat...
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519,george bank recovered daughter wedding receive...

In [29]:
df = df.reset_index(drop = True)

In [30]:
df

,title,overview,genres,tagline,vote_average,popularity,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,7.7,21.946943,led woody andys toy live happily room andys bi...
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539,sibling judy peter discover enchanted board ga...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.712900,family wedding reignites ancient feud nextdoor...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495,cheated mistreated stepped woman holding breat...
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519,george bank recovered daughter wedding receive...
...,...,...,...,...,...,...,...
8958,35 Up,Director Michael Apted revisits the same group...,Documentary Foreign,,7.7,0.930397,director michael apted revisits group britishb...
8959,Days of Being Wild,The movie is set in Hong Kong and the Philippi...,Crime Drama Romance,,7.3,6.242263,movie set hong kong philippine yuddy york engl...
8960,Across the Tracks,When Billy returns from reform school he has t...,Drama,,5.5,1.437157,billy return reform school attend different hi...
8961,Begotten,"Begotten is the creation myth brought to life,...",Fantasy Horror,,5.0,2.592052,begotten creation myth brought life story less...
8962,Life on a String,Two blind men pursue ephemeral and unlikely ho...,Drama Foreign,,7.0,0.071589,two blind men pursue ephemeral unlikely hope o...

In [31]:
indices = pd.Series(df.index, index = df['title']).drop_duplicates() # creating series for indices with movies

In [32]:
indices

title
Toy Story                         0
Jumanji                           1
Grumpier Old Men                  2
Waiting to Exhale                 3
Father of the Bride Part II       4
                               ...
35 Up                          8958
Days of Being Wild             8959
Across the Tracks              8960
Begotten                       8961
Life on a String               8962
Length: 8963, dtype: int64

In [33]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [34]:
tfidf = TfidfVectorizer(ngram_range= (1,2), max_features = 50000, stop_words='english')

In [35]:
tfidf_matrix = tfidf.fit_transform(df['tags'])

In [36]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 350475 stored elements and shape (8963, 50000)>

# **Cosine Similarities**

In [37]:
from sklearn.metrics.pairwise import cosine_similarity

In [38]:
def recommend(title, n=10):
  if title not in indices:
    return ['Movie not found']

  idx = indices[title]
  sim_score = cosine_similarity(tfidf_matrix[idx], tfidf_matrix).flatten()
  similar_idx = sim_score.argsort()[::-1][1:n+1]
  return df['title'].iloc[similar_idx]

In [39]:
recommend('Avatar')

['Movie not found']

In [40]:
import pickle

pickle.dump(tfidf_matrix,open('tfidf_matrix.pkl', 'wb'))

pickle.dump(indices,open('indices.pkl', 'wb'))

df.to_pickle('df.pkl')

pickle.dump(tfidf, open('tfidf.pkl', 'wb'))